name: Demo Failed Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fail_job:
    runs-on: ubuntu-latest

    steps:
    - name: Echo Failed Message
      run: echo "The workflow has failed."

    - name: Set Failed Status
      if: failure()
      run: echo "::set-output name=status::failed"
